package com.example.bank.enums;

public enum Status {
    UNDER_PRE_ANALYSIS,
    UNDER_ANALYSIS_DATA,
    UNDER_ANALYSIS_DOCUMENTS,
    WAITING_FOR_APPROVAL,
    WAITING_FOR_PARTNER_APPROVAL,
    APPROVED,
    RELEASED,
    DENIED,
    CANCELLED
}
